-   id: mdlinker
    name: Markdown Linker
    description: This hook checks that all markdown links are accounted for.
    entry: mdlinker
    language: rust
    pass_filenames: false
-   id: enforce-ascii
    name: Enforce ASCII
    description: This hook replaces all non-ascii characters with ascii characters
    entry: bin/enforce-ascii
    language: python
    pass_filenames: true
