[package]
name = "mdlinker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
env_logger = "0.11.5"
fuzzy-matcher = "0.3.7"
indicatif = "0.17.8"
log = "0.4.22"
miette = { version = "7.2.0", features = ["fancy"] }
rayon = "1.10.0"
regex = "1.10.6"
ripgrep = "14.1.0"
serde = { version = "1.0.208", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "1.0.63"
toml = "0.8.19"
walkdir = "2.5.0"
