name: Deploy Docs to GitHub Pages

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    release:
        name: GitHub Pages
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Git Setup
              run: |
                mkdir -p ~/.ssh
                echo 'Host ${{ vars.SERVER_IP }} ' >> ~/.ssh/config
                echo '    HostName ${{ vars.SERVER_IP }}' >> ~/.ssh/config
                echo '    Port ${{ vars.SERVER_SSH_PORT }}' >> ~/.ssh/config
                cat  ~/.ssh/config

            - uses: actions/checkout@v4
              with:
                ssh-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
                token: ${{ secrets.GITEA_TOKEN }}
                ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                profile: minimal
                override: true
                components: rustfmt, rust-src

            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y librust-alsa-sys-dev pkg-config libudev-dev

            - name: Build Documentation
              env:
                RUSTFLAGS: "-D warnings"
              run: cargo doc --all --no-deps --document-private-items

            - name: Copy "assets/docs" directory
              run: |
                mkdir -p target/doc/assets
                cp -r assets/docs target/doc/assets

            - name: Deploy
              if: github.ref == 'refs/heads/main'
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./target/doc
                publish_branch: gh-pages
